# Generated by Django 4.2.5 on 2023-10-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AddField(
            model_name='bid',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auction.truck'),
        ),
    ]
