# Generated by Django 4.2.6 on 2023-11-25 01:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="cover_image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="auction",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name="AuctionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField()),
                (
                    "auction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auction.auction",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("auction_id", "content_type", "object_id")},
            },
        ),
    ]
