# Generated by Django 4.2.6 on 2023-10-22 02:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="identifier",
        ),
        migrations.AddField(
            model_name="auction",
            name="name",
            field=models.CharField(default="Auction", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auction",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 22, 2, 26, 16, 722675, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="auction",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
