# Generated by Django 4.2.7 on 2024-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0002_auction_end_time_auction_start_time_auctionday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionverifieduser",
            name="cognito_user_id",
            field=models.CharField(max_length=2500),
        ),
    ]
