# Generated by Django 5.0.4 on 2024-04-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0003_alter_auctionverifieduser_cognito_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="end_time",
            field=models.TimeField(default="23:59:59"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="start_time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
