# Generated by Django 5.0.4 on 2024-04-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0004_alter_auction_end_time_alter_auction_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="auction",
            name="start_date",
            field=models.DateField(),
        ),
    ]
