# Generated by Django 5.0.4 on 2024-04-22 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0005_alter_auction_end_date_alter_auction_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="end_time",
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AlterField(
            model_name="auction",
            name="start_time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
