# Generated by Django 4.2.5 on 2023-09-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auction',
            field=models.ManyToManyField(to='auction.auction'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
