# Generated by Django 4.2.6 on 2023-11-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidder",
            name="bidder_number",
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bidder",
            name="company_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
