# Generated by Django 4.2.7 on 2023-11-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_bidder_bidder_number_alter_bidder_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
