# Generated by Django 4.2.6 on 2024-01-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0003_savedunits"),
        ("user", "0003_remove_admin_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidder",
            name="saved_list",
            field=models.ManyToManyField(to="vehicle.vehicle"),
        ),
    ]
