name: Build Python and Django

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        type: string
        default: '3.10'
    secrets:
      django_secret:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python_verison }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
  
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Makes sure it runs
        env:
          SECRET_KEY: ${{ secrets.django_secret }}
        run: |
          pipenv run python manage.py check

