# Generated by Django 4.2.5 on 2023-10-07 23:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
