# Generated by Django 4.2.6 on 2023-10-22 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bid", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="identifier",
        ),
        migrations.AlterField(
            model_name="bid",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
