# Generated by Django 4.2.7 on 2024-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bid", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.CharField(max_length=500),
        ),
    ]
