# Generated by Django 4.2.6 on 2023-11-25 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0002_auction_cover_image_auction_is_published_and_more"),
        ("bid", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="auction.auction",
            ),
            preserve_default=False,
        ),
    ]
