# Generated by Django 5.0.4 on 2024-04-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0003_alter_auctionverifieduser_cognito_user_id"),
        ("bid", "0002_alter_bid_bidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="auction_day",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="auction.auctionday",
            ),
            preserve_default=False,
        ),
    ]
