# Generated by Django 5.0.4 on 2024-04-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trailer",
            name="number_of_axles",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
