# Generated by Django 4.2.6 on 2023-11-17 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="hydraulic_cylindar_condition",
            new_name="hydraulic_cylinder_condition",
        ),
    ]
