# Generated by Django 4.2.6 on 2023-10-22 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="vehicletype",
            name="identifier",
        ),
        migrations.AlterField(
            model_name="brand",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
