# Generated by Django 5.0.4 on 2024-04-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="minimum_price",
            new_name="current_price",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="prefix_id",
        ),
        migrations.RemoveField(
            model_name="trailer",
            name="chassis_number",
        ),
        migrations.AddField(
            model_name="equipment",
            name="current_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="model_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="selling_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="equipment",
            name="starting_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trailer",
            name="current_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailer",
            name="model_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="trailer",
            name="selling_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trailer",
            name="starting_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="chassis_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="engine_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
