# Generated by Django 4.2.7 on 2024-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="engine_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="selling_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="starting_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
