# Generated by Django 5.0.4 on 2024-04-11 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0002_rename_minimum_price_vehicle_current_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="equipment_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="trailer",
            old_name="trailer_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="vehicle_type",
            new_name="type",
        ),
    ]
