name: Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run Python workflow
      uses: ubclaunchpad/microvan/.github/workflows/backend/python.yml@main
      with:
        django_secret: ${{ secrets.DJANGO_SECRET }}

